name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - PranijJoshi
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please enter your name or email
      placeholder: ex. Pranij or pranij@gmail.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Device
    attributes:
      label: What device are you seeing the problem on?
      multiple: false
      options:
        - IOS
        - Android
        - Windows
        - Mac
    validations:
      required: True
    - type: file
      id: images
      attributes:
        label: Attach Images for references
        description: Please attach any relevant images
        multiple: true
  
