name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - PranijJoshi
body:
  - type: input
    id: name
    attributes:
      label: Logged By
      description: Please enter your name or email
      placeholder: ex. Pranij or pranij@gmail.com
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Reported on
      description: Select the date the bug was encountered
      placeholder: Select the date
    validations:
      required: true
  - type: input
    id: epicFeatures
    attributes:
      label: Epic Features
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: urls
    attributes:
      label: URL
      description: Please include the URL of the bug
      placeholder: URL     
  - type: input
    id: title
    attributes:
      label: Title
      description: TITLE FOR THE BUG
      placeholder: title
    validations:
      required: true
  - type: input
    id: Description
    attributes: 
      label: description
      description: Brief description of the reported bug
      placeholder: description
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      multiple: False
      options: 
        - High
        - Medium 
        - Low
  - type: input 
    id: environment
    attributes:
      label: Environment
      description: environment
      placeholder: environment
  - type: input
    id: images
    attributes:
      label: Attach Images for references
      description: Please attach any relevant images
  - type: input 
    id: reproduce
    attributes:
      label: How to Reproduce
      description: How to encounter the bug
      placeholder: How to reproduce the bug
    validations: 
      required: true
  - type: input
    id: behavior
    attributes:
      label: Expected Behavior 
      description: What was the functionality
      placeholder: How should it have functioned??
    validations:
      required: true
    
